### ISSUE TITLE
git history for the imported code

### ISSUE THREAD

**Issue by dimpase** [kliem/memory_allocator#4]
Please make sure the history of the imported  code is imported. After all we'll remove memory_allocator from Sage at some point, replacing it with this fork, and it's good to have it all here.

**Comment by kliem** [comment]
Thanks. I wasn't aware that this is possible. But after all it isn't too hard. So I rebased main on the sage history.

For anyone reading this, wondering how to do it:

https://medium.com/@ayushya/move-directory-from-one-repository-to-another-preserving-git-history-d210fa049d4b
